name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install OpenSSL Development Packages
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Set release tag
      id: set_tag
      run: |
        tag=$(git rev-parse --short=8 ${{ github.sha }})
        echo "tag=${tag}" >> $GITHUB_ENV

    - name: Run tests for Linux x86-64
      run: cargo test --target x86_64-unknown-linux-gnu

    - name: Build for Linux x86-64
      run: |
        rustup target add x86_64-unknown-linux-gnu
        cargo build --release --target x86_64-unknown-linux-gnu
        cp target/x86_64-unknown-linux-gnu/release/mimesorter ./mimesorter-linux-x86_64

    - name: Generate Changelog
      run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        files: |
          changelog.txt
          mimesorter-linux-x86_64
        body_path: changelog.txt
        tag_name: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Set release tag
      id: set_tag
      run: |
        tag=$(git rev-parse --short=8 ${{ github.sha }})
        echo "tag=${tag}" >> $GITHUB_ENV

    - name: Run tests for macOS x86-64
      run: cargo test --target x86_64-apple-darwin

    - name: Build for macOS x86-64
      run: |
        rustup target add x86_64-apple-darwin
        cargo build --release --target x86_64-apple-darwin
        cp target/x86_64-apple-darwin/release/mimesorter ./mimesorter-darwin-x86_64

    - name: Generate Changelog
      run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        files: |
          changelog.txt
          mimesorter-darwin-x86_64
        body_path: changelog.txt
        tag_name: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build-macos-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Set release tag
      id: set_tag
      run: |
        tag=$(git rev-parse --short=8 ${{ github.sha }})
        echo "tag=${tag}" >> $GITHUB_ENV

    - name: Run tests for macOS ARM64
      run: cargo test --target aarch64-apple-darwin

    - name: Build for macOS ARM64
      run: |
        rustup target add aarch64-apple-darwin
        cargo build --release --target aarch64-apple-darwin
        cp target/aarch64-apple-darwin/release/mimesorter ./mimesorter-darwin-arm64

    - name: Generate Changelog
      run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        files: |
          changelog.txt
          mimesorter-darwin-arm64
        body_path: changelog.txt
        tag_name: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-msvc

    - name: Set release tag
      id: set_tag
      shell: powershell
      run: |
        $tag = git rev-parse --short=8 $env:GITHUB_SHA
        Add-Content $env:GITHUB_ENV "tag=$tag"

    - name: Run tests for Windows x86-64
      run: cargo test --target x86_64-pc-windows-msvc

    - name: Build for Windows x86-64
      run: |
        cargo build --release --target x86_64-pc-windows-msvc
        ls target/x86_64-pc-windows-msvc/release/
        cp target/x86_64-pc-windows-msvc/release/mimesorter.exe ./mimesorter-windows-x86_64.exe

    - name: Generate Changelog
      run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref == 'refs/heads/main' && !cancelled() }}
      with:
        files: |
          changelog.txt
          mimesorter-windows-x86_64.exe
        body_path: changelog.txt
        tag_name: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
